# Generated by Django 5.2.8 on 2025-12-22 05:56

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('short_description', models.CharField(max_length=179)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icon', to='core.icon')),
            ],
            options={
                'verbose_name': 'Add Service',
                'verbose_name_plural': 'Add Service',
            },
        ),
        migrations.CreateModel(
            name='Service_Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=159)),
                ('paragraph', models.TextField()),
                ('image_alt', models.CharField(blank=True, max_length=150)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_benefits_images', to='core.media')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_benefits', to='services.add_service')),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefit',
            },
        ),
        migrations.CreateModel(
            name='Service_BenefitRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_color', colorfield.fields.ColorField(blank=True, default='#ae63e4', image_field=None, max_length=25, null=True, samples=None)),
                ('heading', models.CharField(max_length=55)),
                ('paragraph', models.TextField(max_length=455)),
                ('image_alt', models.CharField(blank=True, max_length=256)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.icon')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_rows', to='services.service_benefits')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=159)),
                ('paragraph', models.TextField()),
                ('image_alt', models.CharField(max_length=150)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_details_images', to='core.media')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='services.add_service')),
            ],
            options={
                'verbose_name': 'Details',
                'verbose_name_plural': 'Details',
            },
        ),
        migrations.CreateModel(
            name='Service_DetailBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_color', colorfield.fields.ColorField(blank=True, default='#ae63e4', image_field=None, max_length=25, null=True, samples=None)),
                ('text', models.CharField(max_length=150)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.icon')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bullets', to='services.service_details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service_Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=159)),
                ('paragraph', models.TextField()),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_hero', to='services.add_service')),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Header',
            },
        ),
        migrations.CreateModel(
            name='Service_Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=65)),
                ('meta_description', models.CharField(max_length=159)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated keywords', max_length=255)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=65)),
                ('og_description', models.CharField(blank=True, max_length=160)),
                ('twitter_title', models.CharField(blank=True, max_length=65)),
                ('twitter_description', models.CharField(blank=True, max_length=160)),
                ('no_index', models.BooleanField(default=False)),
                ('no_follow', models.BooleanField(default=False)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_meta', to='services.add_service')),
                ('twitter_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media')),
            ],
            options={
                'verbose_name': 'Meta Data',
                'verbose_name_plural': 'Meta Data',
            },
        ),
        migrations.CreateModel(
            name='WhyChoose_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=15)),
                ('short_paragraph', models.TextField()),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_service', to='services.add_service')),
            ],
            options={
                'verbose_name': 'Our Service',
                'verbose_name_plural': 'Our Service',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_color', colorfield.fields.ColorField(blank=True, default='#ae63e4', image_field=None, max_length=25, null=True, samples=None)),
                ('heading', models.CharField(max_length=55)),
                ('paragraph', models.TextField(max_length=455)),
                ('image_alt', models.CharField(blank=True, max_length=256)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.icon')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whychoose_service_rows', to='services.whychoose_us')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
