# Generated by Django 5.2.8 on 2025-11-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_add_service_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_Sections',
            new_name='Service_page',
        ),
    ]
