# Generated by Django 5.2.8 on 2025-11-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_service_sections_service_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_page',
            new_name='Service_Details',
        ),
    ]
