# Generated by Django 5.2.8 on 2025-11-21 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bulletpoint_row'),
        ('services', '0005_sectionbullet_sectionrow_servicesection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionrow',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='sectionrow',
            name='section',
        ),
        migrations.RemoveField(
            model_name='servicesection',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='servicesection',
            name='section_type',
        ),
        migrations.RemoveField(
            model_name='servicesection',
            name='service',
        ),
        migrations.CreateModel(
            name='ServiceBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('paragraph', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/benefits/')),
                ('image_alt', models.CharField(blank=True, max_length=150)),
                ('rows', models.ManyToManyField(blank=True, to='core.row')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='services.add_service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('paragraph', models.TextField()),
                ('image', models.ImageField(upload_to='services/details/')),
                ('image_alt', models.CharField(max_length=150)),
                ('bullets', models.ManyToManyField(blank=True, to='core.bulletpoint')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='services.add_service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('paragraph', models.TextField()),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='services.add_service')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=150)),
                ('short_paragraph', models.TextField()),
                ('rows', models.ManyToManyField(blank=True, to='core.row')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose', to='services.add_service')),
            ],
        ),
        migrations.DeleteModel(
            name='SectionBullet',
        ),
        migrations.DeleteModel(
            name='SectionRow',
        ),
        migrations.DeleteModel(
            name='ServiceSection',
        ),
    ]
