# Generated by Django 5.2.8 on 2025-11-21 06:03

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_sectiontype_bulletpoint_icon_row_icon'),
        ('services', '0006_remove_sectionrow_icon_remove_sectionrow_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebenefits',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='servicedetails',
            name='bullets',
        ),
        migrations.RemoveField(
            model_name='whychooseus',
            name='rows',
        ),
        migrations.CreateModel(
            name='ServiceBenefitRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_color', colorfield.fields.ColorField(default='#ae63e4', image_field=None, max_length=25, samples=None)),
                ('heading', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/rows/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.icon')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='services.servicebenefits')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetailBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_color', colorfield.fields.ColorField(default='#ae63e4', image_field=None, max_length=25, samples=None)),
                ('text', models.CharField(max_length=150)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.icon')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='services.servicedetails')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUsRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_color', colorfield.fields.ColorField(default='#ae63e4', image_field=None, max_length=25, samples=None)),
                ('heading', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/why/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.icon')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='services.whychooseus')),
            ],
        ),
    ]
