# Generated by Django 5.2.8 on 2025-11-21 06:20

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_servicebenefits_rows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebenefitrow',
            name='heading',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='servicebenefitrow',
            name='icon_color',
            field=colorfield.fields.ColorField(blank=True, default='#ae63e4', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='servicebenefitrow',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rows/'),
        ),
        migrations.AlterField(
            model_name='servicebenefitrow',
            name='paragraph',
            field=models.TextField(max_length=455),
        ),
        migrations.AlterField(
            model_name='whychooseusrow',
            name='heading',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='whychooseusrow',
            name='icon_color',
            field=colorfield.fields.ColorField(blank=True, default='#ae63e4', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='whychooseusrow',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rows/'),
        ),
        migrations.AlterField(
            model_name='whychooseusrow',
            name='paragraph',
            field=models.TextField(max_length=455),
        ),
    ]
