# Generated by Django 5.2.8 on 2025-11-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_servicebenefitrow_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebenefitrow',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/rows/'),
        ),
        migrations.AlterField(
            model_name='servicebenefits',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/static/benefits/'),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='image',
            field=models.ImageField(upload_to='services/static/details/'),
        ),
        migrations.AlterField(
            model_name='whychooseusrow',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/static/rows/'),
        ),
    ]
