# Generated by Django 5.2.8 on 2025-11-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_servicebenefitrow_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebenefitrow',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/media/rows/'),
        ),
        migrations.AlterField(
            model_name='servicebenefits',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/media/benefits/'),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='image',
            field=models.ImageField(upload_to='services/media/details/'),
        ),
        migrations.AlterField(
            model_name='whychooseusrow',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/media/rows/'),
        ),
    ]
