# Generated by Django 5.2.8 on 2025-11-22 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_servicebenefitrow_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebenefitrow',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='core/rows/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'], message="Upload a valid image. The file you uploaded was either not an image or a corrupted image. ['jpg', 'jpeg', 'png', 'webp']")]),
        ),
        migrations.AlterField(
            model_name='servicebenefits',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='services/benefits/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'], message="Upload a valid image. The file you uploaded was either not an image or a corrupted image. ['jpg', 'jpeg', 'png', 'webp']")]),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='image',
            field=models.FileField(null=True, upload_to='services/details/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'], message="Upload a valid image. The file you uploaded was either not an image or a corrupted image. ['jpg', 'jpeg', 'png', 'webp']")]),
        ),
        migrations.AlterField(
            model_name='whychooseusrow',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='core/rows/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'], message="Upload a valid image. The file you uploaded was either not an image or a corrupted image. ['jpg', 'jpeg', 'png', 'webp']")]),
        ),
    ]
