# Generated by Django 5.2.8 on 2025-11-26 05:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_row_icon_delete_bulletpoint_delete_row'),
        ('services', '0014_alter_servicebenefitrow_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_service',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icon', to='core.icon'),
        ),
        migrations.AlterField(
            model_name='servicebenefitrow',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='core/rows/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='servicebenefits',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='services/benefits/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='image',
            field=models.FileField(null=True, upload_to='services/details/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='whychooseusrow',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='core/rows/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.CreateModel(
            name='ServiceMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=65)),
                ('meta_description', models.CharField(max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated keywords', max_length=255)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=65)),
                ('og_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/')),
                ('twitter_title', models.CharField(blank=True, max_length=65)),
                ('twitter_description', models.CharField(blank=True, max_length=160)),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='seo/twitter/')),
                ('no_index', models.BooleanField(default=False)),
                ('no_follow', models.BooleanField(default=False)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_meta', to='services.add_service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
