# Generated by Django 5.2.8 on 2025-12-05 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=259)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Form',
                'verbose_name_plural': 'Contact Form',
            },
        ),
        migrations.CreateModel(
            name='Contact_Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=65)),
                ('meta_description', models.CharField(max_length=159)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated keywords', max_length=255)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=65)),
                ('og_description', models.CharField(blank=True, max_length=160)),
                ('twitter_title', models.CharField(blank=True, max_length=65)),
                ('twitter_description', models.CharField(blank=True, max_length=160)),
                ('no_index', models.BooleanField(default=False)),
                ('no_follow', models.BooleanField(default=False)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media')),
                ('twitter_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media')),
            ],
            options={
                'verbose_name': 'Meta Data',
                'verbose_name_plural': 'Meta Data',
                'abstract': False,
            },
        ),
    ]
