# Generated by Django 5.2.8 on 2026-02-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectdemo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdemo',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('Portfolio', 'Portfolio'), ('Blog', 'Blog'), ('E-Commerce', 'E-Commerce'), ('Landing-Page', 'Landing-Page')], max_length=50),
        ),
    ]
