

icons = [
    ("bi bi-house", "House"),
    ("bi bi-house-fill", "House Fill"),
    ("bi bi-speedometer2", "Speedometer"),
    ("bi bi-search", "Search"),
    ("bi bi-person", "Person"),
    ("bi bi-person-fill", "Person Fill"),
    ("bi bi-people", "People"),
    ("bi bi-people-fill", "People Fill"),
    ("bi bi-list", "List"),
    ("bi bi-menu-button", "Menu Button"),
    ("bi bi-bell", "Bell"),
    ("bi bi-bell-fill", "Bell Fill"),
    ("bi bi-gear", "Gear"),
    ("bi bi-gear-fill", "Gear Fill"),
    ("bi bi-heart", "Heart"),
    ("bi bi-heart-fill", "Heart Fill"),
    ("bi bi-star", "Star"),
    ("bi bi-star-fill", "Star Fill"),
    ("bi bi-check-circle", "Check Circle"),
    ("bi bi-check-circle-fill", "Check Circle Fill"),
    ("bi bi-x-circle", "X Circle"),
    ("bi bi-x-circle-fill", "X Circle Fill"),
    ("bi bi-info-circle", "Info Circle"),
    ("bi bi-info-circle-fill", "Info Circle Fill"),
    ("bi bi-question-circle", "Question Circle"),
    ("bi bi-question-circle-fill", "Question Circle Fill"),
    ("bi bi-exclamation-circle", "Exclamation Circle"),
    ("bi bi-exclamation-circle-fill", "Exclamation Circle Fill"),
    ("bi bi-arrow-right", "Arrow Right"),
    ("bi bi-arrow-left", "Arrow Left"),
    ("bi bi-arrow-up", "Arrow Up"),
    ("bi bi-arrow-down", "Arrow Down"),
    ("bi bi-chevron-right", "Chevron Right"),
    ("bi bi-chevron-left", "Chevron Left"),
    ("bi bi-chevron-up", "Chevron Up"),
    ("bi bi-chevron-down", "Chevron Down"),
    ("bi bi-cart", "Cart"),
    ("bi bi-cart-fill", "Cart Fill"),
    ("bi bi-bag", "Bag"),
    ("bi bi-bag-fill", "Bag Fill"),
    ("bi bi-box-arrow-right", "Box Arrow Right"),
    ("bi bi-box-arrow-left", "Box Arrow Left"),
    ("bi bi-file", "File"),
    ("bi bi-file-earmark", "File Earmark"),
    ("bi bi-file-text", "File Text"),
    ("bi bi-file-earmark-text", "File Earmark Text"),
    ("bi bi-folder", "Folder"),
    ("bi bi-folder-fill", "Folder Fill"),
    ("bi bi-folder2", "Folder2"),
    ("bi bi-folder2-open", "Folder2 Open"),
    ("bi bi-link-45deg", "Link"),
    ("bi bi-globe", "Globe"),
    ("bi bi-grid", "Grid"),
    ("bi bi-grid-1x2", "Grid 1x2"),
    ("bi bi-layout-text-window-reverse", "Layout Text Window Reverse"),
    ("bi bi-journal-text", "Journal Text"),
    ("bi bi-calendar", "Calendar"),
    ("bi bi-calendar-date", "Calendar Date"),
    ("bi bi-calendar-event", "Calendar Event"),
    ("bi bi-clock", "Clock"),
    ("bi bi-alarm", "Alarm"),
    ("bi bi-inbox", "Inbox"),
    ("bi bi-inbox-fill", "Inbox Fill"),
    ("bi bi-envelope", "Envelope"),
    ("bi bi-envelope-fill", "Envelope Fill"),
    ("bi bi-chat", "Chat"),
    ("bi bi-chat-dots", "Chat Dots"),
    ("bi bi-chat-left-dots", "Chat Left Dots"),
    ("bi bi-telephone", "Telephone"),
    ("bi bi-telephone-fill", "Telephone Fill"),
    ("bi bi-hdd", "HDD"),
    ("bi bi-hdd-fill", "HDD Fill"),
    ("bi bi-cpu", "CPU"),
    ("bi bi-gpu-card", "GPU Card"),
    ("bi bi-wifi", "WiFi"),
    ("bi bi-wifi-off", "WiFi Off"),
    ("bi bi-broadcast", "Broadcast"),
    ("bi bi-download", "Download"),
    ("bi bi-upload", "Upload"),
    ("bi bi-cloud", "Cloud"),
    ("bi bi-cloud-fill", "Cloud Fill"),
    ("bi bi-cloud-upload", "Cloud Upload"),
    ("bi bi-cloud-download", "Cloud Download"),
    ("bi bi-play-circle", "Play Circle"),
    ("bi bi-pause-circle", "Pause Circle"),
    ("bi bi-stop-circle", "Stop Circle"),
    ("bi bi-mic", "Mic"),
    ("bi bi-mic-mute", "Mic Mute"),
    ("bi bi-camera", "Camera"),
    ("bi bi-camera-video", "Camera Video"),
    ("bi bi-image", "Image"),
    ("bi bi-images", "Images"),
    ("bi bi-bar-chart", "Bar Chart"),
    ("bi bi-bar-chart-line", "Bar Chart Line"),
    ("bi bi-pie-chart", "Pie Chart"),
    ("bi bi-lightning", "Lightning"),
    ("bi bi-lightning-fill", "Lightning Fill"),
    ("bi bi-shield", "Shield"),
    ("bi bi-shield-lock", "Shield Lock"),
    ("bi bi-lock", "Lock"),
    ("bi bi-unlock", "Unlock")
]
