icons = [
    ("House", "bi bi-house"),
    ("House Fill", "bi bi-house-fill"),
    ("Speedometer", "bi bi-speedometer2"),
    ("Search", "bi bi-search"),
    ("Person", "bi bi-person"),
    ("Person Fill", "bi bi-person-fill"),
    ("People", "bi bi-people"),
    ("People Fill", "bi bi-people-fill"),
    ("List", "bi bi-list"),
    ("Menu Button", "bi bi-menu-button"),
    ("Bell", "bi bi-bell"),
    ("Bell Fill", "bi bi-bell-fill"),
    ("Gear", "bi bi-gear"),
    ("Gear Fill", "bi bi-gear-fill"),
    ("Heart", "bi bi-heart"),
    ("Heart Fill", "bi bi-heart-fill"),
    ("Star", "bi bi-star"),
    ("Star Fill", "bi bi-star-fill"),
    ("Check Circle", "bi bi-check-circle"),
    ("Check Circle Fill", "bi bi-check-circle-fill"),
    ("X Circle", "bi bi-x-circle"),
    ("X Circle Fill", "bi bi-x-circle-fill"),
    ("Info Circle", "bi bi-info-circle"),
    ("Info Circle Fill", "bi bi-info-circle-fill"),
    ("Question Circle", "bi bi-question-circle"),
    ("Question Circle Fill", "bi bi-question-circle-fill"),
    ("Exclamation Circle", "bi bi-exclamation-circle"),
    ("Exclamation Circle Fill", "bi bi-exclamation-circle-fill"),
    ("Arrow Right", "bi bi-arrow-right"),
    ("Arrow Left", "bi bi-arrow-left"),
    ("Arrow Up", "bi bi-arrow-up"),
    ("Arrow Down", "bi bi-arrow-down"),
    ("Chevron Right", "bi bi-chevron-right"),
    ("Chevron Left", "bi bi-chevron-left"),
    ("Chevron Up", "bi bi-chevron-up"),
    ("Chevron Down", "bi bi-chevron-down"),
    ("Cart", "bi bi-cart"),
    ("Cart Fill", "bi bi-cart-fill"),
    ("Bag", "bi bi-bag"),
    ("Bag Fill", "bi bi-bag-fill"),
    ("Box Arrow Right", "bi bi-box-arrow-right"),
    ("Box Arrow Left", "bi bi-box-arrow-left"),
    ("File", "bi bi-file"),
    ("File Earmark", "bi bi-file-earmark"),
    ("File Text", "bi bi-file-text"),
    ("File Earmark Text", "bi bi-file-earmark-text"),
    ("Folder", "bi bi-folder"),
    ("Folder Fill", "bi bi-folder-fill"),
    ("Folder2", "bi bi-folder2"),
    ("Folder2 Open", "bi bi-folder2-open"),
    ("Link", "bi bi-link-45deg"),
    ("Globe", "bi bi-globe"),
    ("Grid", "bi bi-grid"),
    ("Grid 1x2", "bi bi-grid-1x2"),
    ("Layout Text Window Reverse", "bi bi-layout-text-window-reverse"),
    ("Journal Text", "bi bi-journal-text"),
    ("Calendar", "bi bi-calendar"),
    ("Calendar Date", "bi bi-calendar-date"),
    ("Calendar Event", "bi bi-calendar-event"),
    ("Clock", "bi bi-clock"),
    ("Alarm", "bi bi-alarm"),
    ("Inbox", "bi bi-inbox"),
    ("Inbox Fill", "bi bi-inbox-fill"),
    ("Envelope", "bi bi-envelope"),
    ("Envelope Fill", "bi bi-envelope-fill"),
    ("Chat", "bi bi-chat"),
    ("Chat Dots", "bi bi-chat-dots"),
    ("Chat Left Dots", "bi bi-chat-left-dots"),
    ("Telephone", "bi bi-telephone"),
    ("Telephone Fill", "bi bi-telephone-fill"),
    ("HDD", "bi bi-hdd"),
    ("HDD Fill", "bi bi-hdd-fill"),
    ("CPU", "bi bi-cpu"),
    ("GPU Card", "bi bi-gpu-card"),
    ("WiFi", "bi bi-wifi"),
    ("WiFi Off", "bi bi-wifi-off"),
    ("Broadcast", "bi bi-broadcast"),
    ("Download", "bi bi-download"),
    ("Upload", "bi bi-upload"),
    ("Cloud", "bi bi-cloud"),
    ("Cloud Fill", "bi bi-cloud-fill"),
    ("Cloud Upload", "bi bi-cloud-upload"),
    ("Cloud Download", "bi bi-cloud-download"),
    ("Play Circle", "bi bi-play-circle"),
    ("Pause Circle", "bi bi-pause-circle"),
    ("Stop Circle", "bi bi-stop-circle"),
    ("Mic", "bi bi-mic"),
    ("Mic Mute", "bi bi-mic-mute"),
    ("Camera", "bi bi-camera"),
    ("Camera Video", "bi bi-camera-video"),
    ("Image", "bi bi-image"),
    ("Images", "bi bi-images"),
    ("Bar Chart", "bi bi-bar-chart"),
    ("Bar Chart Line", "bi bi-bar-chart-line"),
    ("Pie Chart", "bi bi-pie-chart"),
    ("Lightning", "bi bi-lightning"),
    ("Lightning Fill", "bi bi-lightning-fill"),
    ("Shield", "bi bi-shield"),
    ("Shield Lock", "bi bi-shield-lock"),
    ("Lock", "bi bi-lock"),
    ("Unlock", "bi bi-unlock"),
]
