# Generated by Django 5.2.8 on 2025-12-22 05:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(max_length=255, upload_to=core.models.upload_to_extension_based)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media File',
            },
        ),
        # migrations.CreateModel(
        #     name='ProjectDemo',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=200)),
        #         ('slug', models.SlugField(blank=True, unique=True)),
        #         ('category', models.CharField(choices=[('business', 'Business'), ('portfolio', 'Portfolio'), ('blog', 'Blog'), ('ecommerce', 'E-Commerce'), ('landing', 'Landing Page')], max_length=50)),
        #         ('zip_file', models.FileField(upload_to=core.models.demo_zip_upload_path, validators=[core.models.validate_zip_file])),
        #         ('project_path', models.CharField(blank=True, editable=False, max_length=500)),
        #         ('is_active', models.BooleanField(default=True)),
        #         ('uploaded_at', models.DateTimeField(auto_now_add=True)),
        #     ],
        #     options={
        #         'verbose_name': 'Upload Project',
        #         'verbose_name_plural': 'Upload Projects',
        #     },
        # ),
    ]
