# Generated by Django 5.2.8 on 2025-11-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('use_heading', models.BooleanField(default=True)),
                ('use_paragraph', models.BooleanField(default=True)),
                ('use_image', models.BooleanField(default=False)),
                ('use_image_alt', models.BooleanField(default=False)),
                ('use_icon', models.BooleanField(default=False)),
                ('use_bullets', models.BooleanField(default=False)),
                ('use_rows', models.BooleanField(default=False)),
            ],
        ),
    ]
