# Generated by Django 5.2.8 on 2025-11-21 05:53

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sectiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_color', colorfield.fields.ColorField(default='#ae63e4', image_field=None, max_length=25, samples=None)),
                ('text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_color', colorfield.fields.ColorField(blank=True, default='#ae63e4', image_field=None, max_length=25, null=True, samples=None)),
                ('heading', models.CharField(max_length=55)),
                ('paragraph', models.TextField(max_length=455)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rows/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
