# Generated by Django 5.2.8 on 2025-11-21 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bulletpoint_row'),
        ('services', '0006_remove_sectionrow_icon_remove_sectionrow_section_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectionType',
        ),
        migrations.AddField(
            model_name='bulletpoint',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.icon'),
        ),
        migrations.AddField(
            model_name='row',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.icon'),
        ),
    ]
