# Generated by Django 5.2.8 on 2025-11-21 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_sectiontype_bulletpoint_icon_row_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='icon',
        ),
        migrations.DeleteModel(
            name='BulletPoint',
        ),
        migrations.DeleteModel(
            name='Row',
        ),
    ]
