# Generated by Django 5.2.8 on 2025-12-05 15:54

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs_Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=456)),
            ],
            options={
                'verbose_name': 'Our Benefit',
                'verbose_name_plural': 'Our Benefits',
            },
        ),
        migrations.CreateModel(
            name='Hero_SectionIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=256)),
                ('img_alt', models.CharField(max_length=55)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='index_images', to='core.media')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='Index_Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=65)),
                ('meta_description', models.CharField(max_length=159)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated keywords', max_length=255)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=65)),
                ('og_description', models.CharField(blank=True, max_length=160)),
                ('twitter_title', models.CharField(blank=True, max_length=65)),
                ('twitter_description', models.CharField(blank=True, max_length=160)),
                ('no_index', models.BooleanField(default=False)),
                ('no_follow', models.BooleanField(default=False)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media')),
                ('twitter_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media')),
            ],
            options={
                'verbose_name': 'Meta Data',
                'verbose_name_plural': 'Meta Data',
            },
        ),
        migrations.CreateModel(
            name='Tech_LogoIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_alt', models.CharField(max_length=59)),
                ('logo_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_logo_images', to='core.media')),
            ],
            options={
                'verbose_name': 'Tech Icon',
                'verbose_name_plural': 'Tech Icon',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsRow_Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_color', colorfield.fields.ColorField(blank=True, default='#ae63e4', image_field=None, max_length=25, null=True, samples=None)),
                ('heading', models.CharField(max_length=55)),
                ('paragraph', models.TextField(max_length=455)),
                ('image_alt', models.CharField(blank=True, max_length=256)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.icon')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whychooseus_rows_images', to='index.whychooseus_index')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
