# Generated by Django 5.2.8 on 2025-11-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=260)),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'Data_Created',
            },
        ),
    ]
