# Generated by Django 5.2.8 on 2025-11-22 07:26

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_row_icon_delete_bulletpoint_delete_row'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSectionIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=260)),
                ('background_img', models.ImageField(upload_to='page/index/hero')),
                ('img_alt', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyLogoIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_img', models.ImageField(upload_to='page/index/techlogo')),
                ('img_alt', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUsIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUsRowIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_color', colorfield.fields.ColorField(blank=True, default='#ae63e4', image_field=None, max_length=25, null=True, samples=None)),
                ('heading', models.CharField(max_length=55)),
                ('paragraph', models.TextField(max_length=455)),
                ('image', models.ImageField(blank=True, null=True, upload_to='core/rows/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.icon')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='index.whychooseusindex')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
