# Generated by Django 5.2.8 on 2025-11-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_herosectionindex_background_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technologylogoindex',
            old_name='img_alt',
            new_name='logo_alt',
        ),
        migrations.RenameField(
            model_name='technologylogoindex',
            old_name='background_img',
            new_name='logo_img',
        ),
    ]
