# Generated by Django 5.2.8 on 2025-11-22 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_rename_img_alt_technologylogoindex_logo_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosectionindex',
            name='background_img',
            field=models.FileField(upload_to='page/index/hero', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'], message="Upload a valid image. The file you uploaded was either not an image or a corrupted image. ['jpg', 'jpeg', 'png', 'webp']")]),
        ),
        migrations.AlterField(
            model_name='technologylogoindex',
            name='logo_img',
            field=models.FileField(upload_to='page/index/techlogo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='whychooseusrowindex',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='core/rows/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'], message="Upload a valid image. The file you uploaded was either not an image or a corrupted image. ['jpg', 'jpeg', 'png', 'webp']")]),
        ),
    ]
